# Chapter 2 (More Functions)

In [1]:
import numpy as np

## .reshape( )
- reshapes / converts array of one dimention to another
- the product of dimentions provided should be exactly equal to the number of elements in the matrix (otherwise error)

In [2]:
arr = np.random.randint(1,15,40)
print(arr.shape)
arr

(40,)


array([13,  3,  2,  6,  5,  4,  7,  3, 10,  9, 10, 10,  5,  3, 11,  7, 11,
        1,  8,  2, 14, 12,  8, 13,  7,  9,  5,  5, 12, 10,  1, 14,  4,  1,
       11,  5,  6,  3,  3, 11])

In [3]:
new_arr = arr.reshape(4,10)
print(new_arr.shape)
new_arr

(4, 10)


array([[13,  3,  2,  6,  5,  4,  7,  3, 10,  9],
       [10, 10,  5,  3, 11,  7, 11,  1,  8,  2],
       [14, 12,  8, 13,  7,  9,  5,  5, 12, 10],
       [ 1, 14,  4,  1, 11,  5,  6,  3,  3, 11]])

In [4]:
new_arr = new_arr.reshape(5,8)
print(new_arr.shape)
new_arr

(5, 8)


array([[13,  3,  2,  6,  5,  4,  7,  3],
       [10,  9, 10, 10,  5,  3, 11,  7],
       [11,  1,  8,  2, 14, 12,  8, 13],
       [ 7,  9,  5,  5, 12, 10,  1, 14],
       [ 4,  1, 11,  5,  6,  3,  3, 11]])

In [5]:
new_arr = new_arr.reshape(2,5,4)
print(new_arr.shape)
new_arr

(2, 5, 4)


array([[[13,  3,  2,  6],
        [ 5,  4,  7,  3],
        [10,  9, 10, 10],
        [ 5,  3, 11,  7],
        [11,  1,  8,  2]],

       [[14, 12,  8, 13],
        [ 7,  9,  5,  5],
        [12, 10,  1, 14],
        [ 4,  1, 11,  5],
        [ 6,  3,  3, 11]]])

# Shortcut:
- mention one dimention in .reshape( ) & mention -1 in place of other dimention
- if its possible then the function will calculate it for you
- we can specify only one unknown dimention

In [6]:
arr = np.random.randint(1,10,140)
arr

array([3, 3, 8, 9, 9, 2, 9, 4, 2, 6, 8, 6, 6, 5, 2, 3, 6, 4, 1, 7, 8, 7,
       4, 6, 7, 2, 1, 3, 1, 2, 4, 9, 7, 5, 3, 6, 3, 1, 6, 6, 9, 7, 4, 9,
       8, 3, 2, 3, 5, 8, 3, 4, 6, 2, 7, 3, 9, 5, 1, 9, 8, 6, 9, 8, 9, 6,
       2, 9, 3, 6, 4, 9, 2, 8, 4, 8, 5, 2, 7, 6, 3, 4, 6, 3, 3, 7, 9, 8,
       4, 7, 8, 1, 9, 8, 7, 2, 3, 8, 4, 7, 4, 7, 8, 9, 5, 6, 8, 7, 1, 8,
       4, 9, 9, 8, 3, 9, 6, 4, 2, 5, 8, 2, 1, 7, 5, 9, 1, 8, 1, 6, 6, 4,
       9, 5, 9, 1, 2, 6, 6, 5])

In [7]:
arr = arr.reshape(4,-1)
print(arr.shape)
arr

(4, 35)


array([[3, 3, 8, 9, 9, 2, 9, 4, 2, 6, 8, 6, 6, 5, 2, 3, 6, 4, 1, 7, 8, 7,
        4, 6, 7, 2, 1, 3, 1, 2, 4, 9, 7, 5, 3],
       [6, 3, 1, 6, 6, 9, 7, 4, 9, 8, 3, 2, 3, 5, 8, 3, 4, 6, 2, 7, 3, 9,
        5, 1, 9, 8, 6, 9, 8, 9, 6, 2, 9, 3, 6],
       [4, 9, 2, 8, 4, 8, 5, 2, 7, 6, 3, 4, 6, 3, 3, 7, 9, 8, 4, 7, 8, 1,
        9, 8, 7, 2, 3, 8, 4, 7, 4, 7, 8, 9, 5],
       [6, 8, 7, 1, 8, 4, 9, 9, 8, 3, 9, 6, 4, 2, 5, 8, 2, 1, 7, 5, 9, 1,
        8, 1, 6, 6, 4, 9, 5, 9, 1, 2, 6, 6, 5]])

In [8]:
arr = arr.reshape(-1,7,4)
print(arr.shape)
arr

(5, 7, 4)


array([[[3, 3, 8, 9],
        [9, 2, 9, 4],
        [2, 6, 8, 6],
        [6, 5, 2, 3],
        [6, 4, 1, 7],
        [8, 7, 4, 6],
        [7, 2, 1, 3]],

       [[1, 2, 4, 9],
        [7, 5, 3, 6],
        [3, 1, 6, 6],
        [9, 7, 4, 9],
        [8, 3, 2, 3],
        [5, 8, 3, 4],
        [6, 2, 7, 3]],

       [[9, 5, 1, 9],
        [8, 6, 9, 8],
        [9, 6, 2, 9],
        [3, 6, 4, 9],
        [2, 8, 4, 8],
        [5, 2, 7, 6],
        [3, 4, 6, 3]],

       [[3, 7, 9, 8],
        [4, 7, 8, 1],
        [9, 8, 7, 2],
        [3, 8, 4, 7],
        [4, 7, 8, 9],
        [5, 6, 8, 7],
        [1, 8, 4, 9]],

       [[9, 8, 3, 9],
        [6, 4, 2, 5],
        [8, 2, 1, 7],
        [5, 9, 1, 8],
        [1, 6, 6, 4],
        [9, 5, 9, 1],
        [2, 6, 6, 5]]])

## .ravel( )
- converts a n-D array to one 1-D array

In [50]:
arr = np.random.randint(1,20,12).reshape(2,2,-1)
arr

array([[[ 1, 12, 17],
        [ 5, 14, 13]],

       [[11, 15,  7],
        [10, 14,  7]]])

In [56]:
arr.ravel()

array([ 1, 12, 17,  5, 14, 13, 11, 15,  7, 10, 14,  7])

## .flatten( )
- converts a n-D array to one 1-D array , just like ravel( )

In [57]:
arr = np.random.randint(1,20,12).reshape(4,-1)
arr

array([[ 9,  5,  5],
       [11, 17, 14],
       [18,  2,  6],
       [10,  4,  6]])

In [58]:
arr.flatten()

array([ 9,  5,  5, 11, 17, 14, 18,  2,  6, 10,  4,  6])

## .transpose( )
- transposes the matrix

In [59]:
arr = np.random.randint(1,20,12).reshape(4,-1)
arr

array([[ 1, 17, 13],
       [ 3,  4, 18],
       [ 9,  7, 12],
       [ 8,  4,  7]])

In [61]:
arr.transpose()

array([[ 1,  3,  9,  8],
       [17,  4,  7,  4],
       [13, 18, 12,  7]])

## np.linspace( )
- creates a sequence of numpy array which are evenly spaced
- np.linspace(starting pos, ending pos, number of elements in sequence)

In [41]:
arr = np.linspace(0,100,5)
arr

array([  0.,  25.,  50.,  75., 100.])

In [42]:
arr = np.linspace(10,50,10)
arr

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

## Changing datatype

In [43]:
arr = np.array([0,1,2,1,4,0,-1,0,-2,-3],dtype = 'bool')
arr

array([False,  True,  True,  True,  True, False,  True, False,  True,
        True])

In [44]:
arr = np.array([0,1,2,1,4,0,-1,0,-2,-3],dtype = 'float')
arr

array([ 0.,  1.,  2.,  1.,  4.,  0., -1.,  0., -2., -3.])

In [45]:
arr = np.array([0,1,2,1,4,0,-1,0,-2,-3],dtype = 'str')
arr

array(['0', '1', '2', '1', '4', '0', '-1', '0', '-2', '-3'], dtype='<U2')