In [1]:
import numpy as np

# np.concatenate ( )
- used to concatinate numpy arrays
- by default axis = 0 (column)
- "axis" parameter functions the same way here

In [14]:
arr_1 = np.random.randint(1,20,(4,3))
arr_2 = np.random.randint(1,20,(4,3))
arr_3 = np.random.randint(1,20,(4,3))

In [15]:
print(arr_1)
print('\n')
print(arr_2)
print('\n')
print(arr_3)

[[17  4  7]
 [ 2  8  7]
 [ 3 14 11]
 [13  5  1]]


[[14  8 18]
 [ 7  1  4]
 [19  1  8]
 [16 16  4]]


[[ 9  2 15]
 [ 5  5  3]
 [11  9 16]
 [ 2  5 18]]


In [16]:
np.concatenate((arr_1,arr_2))

array([[17,  4,  7],
       [ 2,  8,  7],
       [ 3, 14, 11],
       [13,  5,  1],
       [14,  8, 18],
       [ 7,  1,  4],
       [19,  1,  8],
       [16, 16,  4]])

In [17]:
np.concatenate((arr_1,arr_2,arr_3),axis = 1)

array([[17,  4,  7, 14,  8, 18,  9,  2, 15],
       [ 2,  8,  7,  7,  1,  4,  5,  5,  3],
       [ 3, 14, 11, 19,  1,  8, 11,  9, 16],
       [13,  5,  1, 16, 16,  4,  2,  5, 18]])

# Horizontal and Vertical stacking
- sizes of matrices should be same

## np.hstack( )
- horizontal stacking/ concatination

In [18]:
np.hstack((arr_1,arr_2))

array([[17,  4,  7, 14,  8, 18],
       [ 2,  8,  7,  7,  1,  4],
       [ 3, 14, 11, 19,  1,  8],
       [13,  5,  1, 16, 16,  4]])

## np.vstack( )
- vertical stacking/ concatination

In [19]:
np.vstack((arr_1,arr_2,arr_3))

array([[17,  4,  7],
       [ 2,  8,  7],
       [ 3, 14, 11],
       [13,  5,  1],
       [14,  8, 18],
       [ 7,  1,  4],
       [19,  1,  8],
       [16, 16,  4],
       [ 9,  2, 15],
       [ 5,  5,  3],
       [11,  9, 16],
       [ 2,  5, 18]])

# np.split( )
- syntax : np.split(array, number of splits, axis)
- splits the array along row-ine or column-line, and retuens a "list"
- here the axis system is reversed ( 0 = row [default] , 1 = column )

In [20]:
arr_1

array([[17,  4,  7],
       [ 2,  8,  7],
       [ 3, 14, 11],
       [13,  5,  1]])

In [26]:
np.split(arr_1,2)

[array([[17,  4,  7],
        [ 2,  8,  7]]),
 array([[ 3, 14, 11],
        [13,  5,  1]])]

In [27]:
np.split(arr_1,4)

[array([[17,  4,  7]]),
 array([[2, 8, 7]]),
 array([[ 3, 14, 11]]),
 array([[13,  5,  1]])]

In [29]:
np.split(arr_1,3, axis=1)

[array([[17],
        [ 2],
        [ 3],
        [13]]),
 array([[ 4],
        [ 8],
        [14],
        [ 5]]),
 array([[ 7],
        [ 7],
        [11],
        [ 1]])]

In [35]:
# here we are splitting row wise 3 parts : 1 row, 2 row, 1 row. we can do that by passing an array.
# here we are providing the index at which the splitting starts.
np.split(arr_1,[1,3])

[array([[17,  4,  7]]),
 array([[ 2,  8,  7],
        [ 3, 14, 11]]),
 array([[13,  5,  1]])]

In [39]:
arr = np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
np.split(arr,[1,4,8,14])

[array([1]),
 array([2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14]),
 array([15])]