In [1]:
import numpy as np

# BODMAS Operations with scaler
- appplies operation to all elements
- doesnt changes the original array , but returns a new array

In [31]:
np.random.seed(5)

arr = np.random.randint(1,15,(3,4))

### addition

In [29]:
arr

array([[ 4, 14,  7,  7],
       [ 1, 10,  9,  5],
       [ 8, 12,  1,  1]])

In [30]:
arr + 5

array([[ 9, 19, 12, 12],
       [ 6, 15, 14, 10],
       [13, 17,  6,  6]])

### substraction

In [33]:
arr # the previous addition operation didnt change the original array

array([[ 4, 14,  7,  7],
       [ 1, 10,  9,  5],
       [ 8, 12,  1,  1]])

In [34]:
arr - 5

array([[-1,  9,  2,  2],
       [-4,  5,  4,  0],
       [ 3,  7, -4, -4]])

### multiplication

In [35]:
arr

array([[ 4, 14,  7,  7],
       [ 1, 10,  9,  5],
       [ 8, 12,  1,  1]])

In [36]:
arr*4

array([[16, 56, 28, 28],
       [ 4, 40, 36, 20],
       [32, 48,  4,  4]])

### division

In [37]:
arr

array([[ 4, 14,  7,  7],
       [ 1, 10,  9,  5],
       [ 8, 12,  1,  1]])

In [38]:
arr/3

array([[1.33333333, 4.66666667, 2.33333333, 2.33333333],
       [0.33333333, 3.33333333, 3.        , 1.66666667],
       [2.66666667, 4.        , 0.33333333, 0.33333333]])

In [39]:
#  in numpy dividing with 0 will give a warning and produce infinity
#  in other cases it gives error

arr/0

<ipython-input-39-0337b591e344>:4: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

### exponent

In [40]:
arr

array([[ 4, 14,  7,  7],
       [ 1, 10,  9,  5],
       [ 8, 12,  1,  1]])

In [41]:
arr**3

array([[  64, 2744,  343,  343],
       [   1, 1000,  729,  125],
       [ 512, 1728,    1,    1]], dtype=int32)

### modulus

In [42]:
arr

array([[ 4, 14,  7,  7],
       [ 1, 10,  9,  5],
       [ 8, 12,  1,  1]])

In [43]:
arr%3

array([[1, 2, 1, 1],
       [1, 1, 0, 2],
       [2, 0, 1, 1]], dtype=int32)

# BODMAS Operation with array / matrices
- does not fully reflect on mathematical matrix operation
- just applies operation on elements present at same location with one another
- will only work with matrices having same size, otherwise it will give error

In [45]:
np.random.seed(56)

m1 = np.random.randint(1,6,(4,4))
m2 = np.random.randint(6,10,(4,4))

print(m1)
print('\n')
print(m2)

[[5 1 3 4]
 [3 2 4 5]
 [2 3 2 1]
 [5 3 4 4]]


[[8 6 7 8]
 [7 7 8 9]
 [6 7 7 8]
 [9 6 7 9]]


### addition

In [52]:
# np.add(m1,m2)
m1 + m2

array([[13,  7, 10, 12],
       [10,  9, 12, 14],
       [ 8, 10,  9,  9],
       [14,  9, 11, 13]])

### substraction

In [55]:
# np.subtract(m2,m1)
m2 - m1

array([[3, 5, 4, 4],
       [4, 5, 4, 4],
       [4, 4, 5, 7],
       [4, 3, 3, 5]])

### division

In [57]:
# np.divide(m2,m1)
m2/m1

array([[1.6       , 6.        , 2.33333333, 2.        ],
       [2.33333333, 3.5       , 2.        , 1.8       ],
       [3.        , 2.33333333, 3.5       , 8.        ],
       [1.8       , 2.        , 1.75      , 2.25      ]])

### multiplication (not matrix multiplication)

In [64]:
# np.multiply(m1,m2)
m2*m1

array([[40,  6, 21, 32],
       [21, 14, 32, 45],
       [12, 21, 14,  8],
       [45, 18, 28, 36]])

### Matrix Multiplication
- to perform dot product, actual matrix multiplication

In [65]:
# m2.dot(m1)
m2@m1

array([[112,  65,  94, 101],
       [117,  72, 101, 107],
       [105,  65,  92,  98],
       [122,  69, 101, 109]])

# Operations Within the Matrix

- there is an axis parameter which takes :
-    0 = column wise
-    1 = row wise

returns data for each column/row

## Statistical functions

### .min( ) & .max( )
- finding minimum and maximum values

In [72]:
np.random.seed(34)

arr = np.random.randint(1,100,(3,3))
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [73]:
arr.min()
# np.min(arr)

12

In [74]:
# column wise data

arr.min(axis = 0)
# np.min(arr, axis = 0)

array([34, 30, 12])

In [75]:
# row wise data

arr.min(axis = 1)

array([34, 12, 19])

In [76]:
arr.max()
# np.max(arr)

86

In [77]:
arr.max(axis = 0)

array([79, 86, 69])

### .argmin( ) & .argmax( )
- finding the position of a minimum, maximum value
- treats even multi dimentional array as vectors
- axis functions similarly here

In [78]:
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [79]:
arr.argmin()
# np.argmin(arr)

5

In [81]:
arr.argmax(axis = 1)

array([1, 1, 0], dtype=int64)

### .sum( )
- adds all element
- axis functions similarly here

In [82]:
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [84]:
arr.sum()
# np.sum(arr)

435

In [85]:
arr.sum(axis = 1)
# np.sum(arr,axis = 1)

array([189, 118, 128])

### .cumsum( )
- gives cumulative sum
- axis functions similarly here

In [86]:
arr.cumsum()
# np.cumsum(arr)

array([ 34, 120, 189, 225, 295, 307, 386, 416, 435], dtype=int32)

In [87]:
arr.cumsum(axis  = 1)

array([[ 34, 120, 189],
       [ 36, 106, 118],
       [ 79, 109, 128]], dtype=int32)

### .prod( )
- gives product of all elements
- axis functions similarly here

In [89]:
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [90]:
arr.prod()
# np.prod(arr)

719787264

In [91]:
arr.prod(axis = 1)

array([201756,  30240,  45030])

### .mean( )
- finding mean
- axis functions similarly here

In [92]:
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [93]:
arr.mean()
# np.mean(arr)

48.333333333333336

In [94]:
arr.mean(axis = 1)

array([63.        , 39.33333333, 42.66666667])

### .std( )
- finding standard deviation
- axis functions similarly here

In [120]:
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [123]:
# np.std(arr)
arr.std()

26.09810550808451

In [124]:
arr.std(axis = 0)

array([20.7578633 , 23.55136231, 25.38153309])

### np.median( ) { cannot be directly applied to the array like others }
- finding median
- axis functions similarly here

In [95]:
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [100]:
np.median(arr)

36.0

In [101]:
np.median(arr, axis = 0)

array([36., 70., 19.])

## Trigonometric, Logarithmic & Exponential functions

### np.pi
- gives the value of pi

In [119]:
np.pi

3.141592653589793

### np.sin( ), np.cos( ), np.tan( )
- finding trigonometric values

In [114]:
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [116]:
np.sin(arr)

array([[ 0.52908269, -0.92345845, -0.11478481],
       [-0.99177885,  0.77389068, -0.53657292],
       [-0.44411267, -0.98803162,  0.14987721]])

In [117]:
np.cos(arr)

array([[-0.84857027, -0.38369844,  0.99339038],
       [-0.12796369,  0.6333192 ,  0.84385396],
       [-0.89597095,  0.15425145,  0.98870462]])

In [118]:
np.tan(arr)

array([[-0.62349896,  2.40672971, -0.11554855],
       [ 7.75047091,  1.22195992, -0.63585993],
       [ 0.49567753, -6.4053312 ,  0.15158947]])

### np.sqrt( ) 
- finding squareroot

In [102]:
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [106]:
np.sqrt(arr)

array([[5.83095189, 9.2736185 , 8.30662386],
       [6.        , 8.36660027, 3.46410162],
       [8.88819442, 5.47722558, 4.35889894]])

### np.exp( )
- finds exponent value of all elements , power of euler's number (e)

In [107]:
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [109]:
np.exp(arr)

array([[5.83461743e+14, 2.23524660e+37, 9.25378173e+29],
       [4.31123155e+15, 2.51543867e+30, 1.62754791e+05],
       [2.03828107e+34, 1.06864746e+13, 1.78482301e+08]])

### np.log( )
- finds log value of all elements , base = e

In [110]:
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [111]:
np.log(arr)

array([[3.52636052, 4.4543473 , 4.2341065 ],
       [3.58351894, 4.24849524, 2.48490665],
       [4.36944785, 3.40119738, 2.94443898]])

### np.log10( )
- finds log value of all elements , base = 10

In [112]:
arr

array([[34, 86, 69],
       [36, 70, 12],
       [79, 30, 19]])

In [113]:
np.log10(arr)

array([[1.53147892, 1.93449845, 1.83884909],
       [1.5563025 , 1.84509804, 1.07918125],
       [1.89762709, 1.47712125, 1.2787536 ]])