# Chapter 5 (Conditional Selection)

In [1]:
import numpy as np

In [24]:
np.random.seed(15)

arr = np.random.randint(1,15,(7,5))
arr

array([[ 9,  6, 13,  6,  8],
       [ 1, 13, 12,  8, 12],
       [ 6,  7, 14,  2, 14],
       [ 8,  1, 11,  5, 10],
       [ 8,  6,  4, 13, 14],
       [13, 14,  7,  9,  3],
       [ 2,  2,  1,  6, 11]])

In [11]:
temp = arr>10
temp

array([[False, False,  True, False, False],
       [False,  True,  True, False,  True],
       [False, False,  True, False,  True],
       [False, False,  True, False, False],
       [False, False, False,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False, False,  True]])

In [12]:
arr[temp]

array([13, 13, 12, 12, 14, 14, 11, 13, 14, 13, 14, 11])

In [25]:
arr[arr%2==0]

array([ 6,  6,  8, 12,  8, 12,  6, 14,  2, 14,  8, 10,  8,  6,  4, 14, 14,
        2,  2,  6])

In [26]:
arr[(arr)%2==0] = 1
arr

array([[ 9,  1, 13,  1,  1],
       [ 1, 13,  1,  1,  1],
       [ 1,  7,  1,  1,  1],
       [ 1,  1, 11,  5,  1],
       [ 1,  1,  1, 13,  1],
       [13,  1,  7,  9,  3],
       [ 1,  1,  1,  1, 11]])