In [1]:
import numpy as np

# np.random.randint( )
- it generates NumPy array of random integers between the range provided
- np.random.randint(1,15,4): generates a NumPy array of 4 elements that belong i the range of - 1------14

In [2]:
array = np.random.randint(1,15,7)
array

array([ 4, 11, 12,  3, 12, 14,  8])

In [3]:
array = np.random.randint(1,15,(4,3))
array

array([[ 1, 10,  7],
       [12, 13, 11],
       [ 4,  4, 10],
       [14,  4,  2]])

In [4]:
array = np.random.randint(1,15,(3,2,4))
array

array([[[ 4, 11,  6,  5],
        [ 3,  9, 11, 12]],

       [[10,  7,  3,  9],
        [ 5,  6, 10, 12]],

       [[14,  3,  7,  8],
        [11,  3,  5, 10]]])

# np.random.random( )
- generates random numbers between 0 - 1 , but can only create 1D array

In [25]:
array = np.random.random(15)
array

array([0.44812066, 0.77490038, 0.7963907 , 0.52239013, 0.4606303 ,
       0.7782136 , 0.88728895, 0.67491877, 0.80047905, 0.93911135,
       0.04065581, 0.87567172, 0.27656307, 0.4757645 , 0.79676096])

# np.random.rand( )
- generates random numbers between 0 - 1 
- unlike np.random.random, it can generate n-D arrays

In [12]:
array = np.random.rand(5)
array

array([0.87350806, 0.5865461 , 0.21723135, 0.88948295, 0.24764357])

In [13]:
array = np.random.rand(2,3)
array

array([[0.96970336, 0.93920538, 0.44663128],
       [0.71089347, 0.51409117, 0.29366011]])

In [14]:
array = np.random.rand(3,2,2)
array

array([[[0.92388096, 0.13190756],
        [0.56044206, 0.05605673]],

       [[0.6077973 , 0.00461853],
        [0.71869656, 0.17930524]],

       [[0.93835496, 0.62459822],
        [0.22569134, 0.3468615 ]]])

# np.random.randn( )
- works like like np.random.rand, generates array of random numbers between 0---1
- but all numbers combined are centered around 0

In [15]:
array = np.random.randn(7)
array

array([-0.39813882, -1.45293478, -0.27506443,  0.206756  , -1.17039157,
       -0.9814288 , -0.08436754])

In [16]:
array = np.random.randn(2,4)
array

array([[ 0.80890761,  1.28312995,  0.86361918,  1.32475777],
       [-0.78043365, -1.87804183,  0.70274126, -0.40392314]])

# np.random.seed( )
- to generate same random number every time
- give a seed number to fix

In [19]:
np.random.seed(7)

arr = np.random.randint(1,100,15)
arr

array([48, 69, 26, 68, 84, 24, 93, 58, 15, 24, 73, 90, 43, 91,  9])

# np.random.shuffle( ) {changes the original array}
- shuffles elements within array

In [35]:
np.random.seed(45)

arr_1 = np.random.randint(1,10,17)
arr_2 = np.random.randint(1,10,(3,3))

In [36]:
arr_1

array([4, 1, 6, 4, 5, 9, 2, 6, 7, 9, 8, 9, 6, 3, 9, 2, 7])

In [32]:
np.random.shuffle(arr_1)
arr_1

array([9, 4, 9, 9, 6, 1, 6, 6, 7, 5, 4, 2, 8, 7, 2, 9, 3])

In [37]:
arr_2

array([[5, 9, 5],
       [7, 5, 2],
       [7, 9, 9]])

In [40]:
np.random.shuffle(arr_2)
arr_2

array([[7, 5, 2],
       [5, 9, 5],
       [7, 9, 9]])

# np.random.permutation( ) {doesnt change the original array}
- shuffles elements within array

In [41]:
arr_1

array([4, 1, 6, 4, 5, 9, 2, 6, 7, 9, 8, 9, 6, 3, 9, 2, 7])

In [42]:
np.random.permutation(arr)

array([69, 91, 90, 58, 24, 73, 68, 93, 26, 43,  9, 15, 24, 84, 48])

In [43]:
arr #no change in array

array([48, 69, 26, 68, 84, 24, 93, 58, 15, 24, 73, 90, 43, 91,  9])

In [44]:
arr_2

array([[7, 5, 2],
       [5, 9, 5],
       [7, 9, 9]])

In [46]:
np.random.permutation(arr_2)

array([[7, 9, 9],
       [5, 9, 5],
       [7, 5, 2]])

# np.random.choice( )
- chooses a random element from an array
- only takes 1D array as input

In [49]:
arr_1

array([4, 1, 6, 4, 5, 9, 2, 6, 7, 9, 8, 9, 6, 3, 9, 2, 7])

In [50]:
np.random.choice(arr_1)

2