# Chapter 1 (Basics)

## Introduction

- Python library designed for scientific computation
- NumPy arrays are main ways to use NumPy library
- Numpy is very fast compared to Python's list
- It is fast because of the binding with c language

some terminologies---

- 1-d array = Vectors
- 2-d array = Matrix 
- n-d array = Tensor 

## Creating A NumPy array

In [1]:
import numpy as np

L = [1,2,3,4,5,6,7,8,9]
L_2D = [[1,3,5,7,9],[2,4,6,8,10]]
L_3D = [[[1,3,5,7,9],[2,4,6,8,10]],[[4,5,6,8,4],[7,9,5,8,4]]]

array = np.array(L)
array_2D = np.array(L_2D)
array_3D = np.array(L_3D)

In [2]:
print(type(array))
array

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(type(array_2D))
array_2D

<class 'numpy.ndarray'>


array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [4]:
print(type(array_3D))
array_3D

<class 'numpy.ndarray'>


array([[[ 1,  3,  5,  7,  9],
        [ 2,  4,  6,  8, 10]],

       [[ 4,  5,  6,  8,  4],
        [ 7,  9,  5,  8,  4]]])

Therory :

- NumPy arrays only store a *single data type*.
- It implicitly changes data type if there are many present.

In [5]:
# all int , no problem

L = [1,2,3,4,5,6,7,8,9]

array = np.array(L)
print(array.dtype)
array

int32


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# one float data, changed the whole array type to float 

L = [1, 2, 3, 4, 5.57, 6, 7, 8, 9]

array = np.array(L)
print(array.dtype)
array

float64


array([1.  , 2.  , 3.  , 4.  , 5.57, 6.  , 7.  , 8.  , 9.  ])

In [7]:
# one str data, changed rhe whole arry type to str

L = [1,2,3,4,5.57,6,7,8,9,'harsh vashista',True,False]

array = np.array(L)
print(array.dtype)
array

<U32


array(['1', '2', '3', '4', '5.57', '6', '7', '8', '9', 'harsh vashista',
       'True', 'False'], dtype='<U32')

In [8]:
# boolean datas are converted to int , in presence of integers
# True = 1
# False = 0

L = [1,2,3,4,5,6,7,8,9,True,False]

array = np.array(L)
print(array.dtype)
array

int32


array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 0])

In [9]:
# inclusion of None makes data type - Object

L = [1,2,3,4,5.57,6,7,8,9,'harsh vashista',True,False,None]

array = np.array(L)
print(array.dtype)
array

object


array([1, 2, 3, 4, 5.57, 6, 7, 8, 9, 'harsh vashista', True, False, None],
      dtype=object)

## Methods & Functions

In [10]:
import numpy as np

L = [1,2,3,4,5,6,7,8,9]
L_2D = [[1,3,5,7,9],[2,4,6,8,10]]
L_3D = [[[1,3,5,7,9],[2,4,6,8,10]],[[4,5,6,8,4],[7,9,5,8,4]]]

array = np.array(L)
array_2D = np.array(L_2D)
array_3D = np.array(L_3D)

### .ndim 
- gives dimention / order of matrix (1D,2D,3D...)

In [11]:
array.ndim , array_2D.ndim , array_3D.ndim

(1, 2, 3)

### .shape
- gives shape of matrix in form of (m\*n)

In [12]:
print(array.shape)
print(array_2D.shape)
print(array_3D.shape)

(9,)
(2, 5)
(2, 2, 5)


### .size
- to count total number of elements in an array 

In [44]:
arr = np.random.randint(1,10,(7,5,4))
arr

array([[[7, 1, 5, 9],
        [1, 3, 7, 8],
        [1, 1, 3, 3],
        [7, 1, 7, 1],
        [9, 9, 1, 7]],

       [[8, 9, 6, 2],
        [4, 8, 6, 4],
        [3, 8, 8, 5],
        [8, 3, 8, 5],
        [6, 8, 8, 7]],

       [[3, 8, 8, 7],
        [7, 4, 7, 1],
        [8, 5, 4, 6],
        [8, 4, 6, 6],
        [8, 2, 1, 3]],

       [[2, 3, 4, 7],
        [4, 7, 2, 2],
        [8, 5, 1, 3],
        [2, 2, 5, 3],
        [3, 3, 6, 4]],

       [[7, 8, 6, 7],
        [6, 3, 9, 8],
        [2, 3, 8, 7],
        [5, 6, 5, 6],
        [5, 2, 4, 8]],

       [[1, 6, 1, 7],
        [6, 9, 1, 2],
        [3, 5, 5, 1],
        [9, 3, 9, 8],
        [6, 5, 4, 3]],

       [[6, 8, 3, 6],
        [9, 1, 9, 5],
        [1, 3, 6, 2],
        [3, 2, 5, 3],
        [4, 8, 1, 3]]])

In [45]:
print(arr.ndim)
print(arr.shape)
print(arr.size)

3
(7, 5, 4)
140


### .dtype
- returns data type of NumPy array

In [13]:
array_2D.dtype

dtype('int32')

### .itemsize
- returns size of each element in bytes

In [43]:
# the dtype was = int32 (32bits = 4bytes)
array_2D.itemsize 

4

### np.zeros( )
- creates an array of given dimention and initializes with zeros
- can also control the datatype of the elements using "dtype" attribute

In [14]:
# 1D array
array = np.zeros(5)
array

array([0., 0., 0., 0., 0.])

In [15]:
# 2D array
array = np.zeros((2,3))
array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# 3D array
array = np.zeros((3,3,5))
array

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [17]:
# changing the datatype
array = np.zeros((3,3), dtype = str) # 0 in python means empty string and False
array

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

### np.ones( )
- creates an array of given dimention and initializes with ones
- "dtype" attribute is used to control the datatype of the elements similar to zeros

In [18]:
array = np.ones(5)
array

array([1., 1., 1., 1., 1.])

In [19]:
array = np.ones((2,3))
array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
array = np.ones((2,5,3))
array

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### np.empty( )
- creates an empty array of given dimention
- empty doesnt necesserily means containing NULL strings, instead the elements have garbage values
- it also has "dtype" attribute

In [21]:
np.empty((3,3))

array([[1.  , 2.  , 3.  ],
       [4.  , 5.57, 6.  ],
       [7.  , 8.  , 9.  ]])

### np.eye( )
- creates an array of given dimention and initializes all diagonals with ones

In [22]:
# single input specifies number of ones
# single input makes square matrix with that many ones in diagonal

array = np.eye(5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# 2 inputs specify dimentions
# ones are fitted into diagonals accordingly

array = np.eye(1,5)
array

array([[1., 0., 0., 0., 0.]])

In [24]:
array = np.eye(4,7)
array

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

In [25]:
# with 3 inputs, the first two inputs are the dimentions of matrix
# the 3rd input is the offset at wich the diagonals become 1

array = np.eye(4,5,2)
array

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### np.diag( )
- takes list / tuple and creates a diagonal matrix with list / tuple elements in diagonal position
- takes a matrix and returns the diagonal elements in it in form of list

In [26]:
array = np.diag([1,2,3,4,5])
array

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [27]:
array = [[1,2,6,5,4],
         [6,45,6,4,3],
         [5,6,8,2,3],
         [5,8,6,2,7]]

diagonal = np.diag(array)
diagonal

array([ 1, 45,  8,  2])

### np.arange( )
- creates array in range provided
- np.arange( starting index , stoping index + 1 , step)

In [28]:
array = np.arange(1,10,2)
array

array([1, 3, 5, 7, 9])

### np.unique( )
- gives all unique elements in array (all elements removing all extras)

In [39]:
arr

array([9, 3, 6, 4, 4, 6, 9, 6, 1, 9, 2, 7, 8, 7, 2, 9, 5])

In [40]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# first array gives all unique array elements
# second array gives the respective first index
#  third array gives count of each elements

np.unique(arr, return_index = True, return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 8, 10,  1,  3, 16,  2, 11, 12,  0], dtype=int64),
 array([1, 2, 1, 2, 1, 3, 2, 1, 4], dtype=int64))